# Compile Squid
- name: Copy Squid packages
  copy:
    src: compilation-scripts/
    dest: /tmp/squid/

- name: Copy Squid debian files
  copy:
    src: debian/
    dest: /tmp/squid/debian/

#- name: Extract libressl into /tmp/squid/libressl
#  unarchive:
#    src: libressl/
#    dest: /tmp/squid/libressl


- name: Changing permissions
  file: dest=/tmp/squid/{{ item }} mode=a+x
  with_items:
    - 02_build_ecap.sh
    - 03_install_ecap.sh
    - 04_build_squid.sh
    - 05_install_squid.sh

- name: Installing tools
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - devscripts
    - build-essential
    - fakeroot
    - cdbs
    - debhelper
    - dh-autoreconf
    - libsasl2-dev
    - libxml2-dev
    - libdb-dev
    - libkrb5-dev
    - nettle-dev
    - libnetfilter-conntrack-dev
    - libpam0g-dev
    - libldap2-dev
    - libcppunit-dev
    - libexpat1-dev
    - libcap2-dev
    - libltdl-dev
    - libssl-dev
    - libdbi-perl
    - squid-langpack
  become: yes
  retries: 30
  delay: 5
  register: update_result
  until: update_result is succeeded

- name: Build ecap
  command: /tmp/squid/02_build_ecap.sh

- name: Install ecap
  command: /tmp/squid/03_install_ecap.sh
  become: yes

- name: Build Squid
  command: /tmp/squid/04_build_squid.sh

# Install Squid
- name: Install Squid
  command: /tmp/squid/05_install_squid.sh
  become: yes

# Configure Squid
- name: Create Squid certificate directory
  become: yes
  file: path=/etc/squid/ssl_cert state=directory

- name: Initialise Squid certificate db
  become: yes
  command: /usr/lib/squid/security_file_certgen -c -s /var/spool/squid/ssl_db -M 4MB

- name: Remove tmp files
  file: path=/tmp/squid/ state=absent

- iptables:
    table: nat
    chain: PREROUTING
    protocol: tcp
    match: tcp
    destination_port: 80
    source: 10.0.0.0/8,192.168.0.0/16,172.16.0.0/12
    jump: REDIRECT
    to_ports: 3128
    comment: Redirect HTTP traffic to port 3128
  become: yes

- iptables:
    table: nat
    chain: PREROUTING
    protocol: tcp
    match: tcp
    destination_port: 443
    source: 10.0.0.0/8,192.168.0.0/16,172.16.0.0/12
    jump: REDIRECT
    to_ports: 3129
    comment: Redirect HTTPS traffic to port 3129
  become: yes

- name: Install `netfilter-persistent` && `iptables-persistent` packages
  package:
    name: "{{item}}"
    state: present
  with_items:
    - iptables-persistent
    - netfilter-persistent
  when: ansible_os_family == "Debian"
  become: true

